baseURL = "https://thakurajayL.github.io/quality-share/"
languageCode = 'en-us'
title = 'Quality Share: A Curated Library for Engineers'
theme = "ananke"

[params]
  description = "High-signal engineering articles, expertly curated. Because your time is too valuable for anything less."
  # Custom params for data sources
  [params.data]
    pipelineDb = "../pipeline/data/pipeline.db"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Decisions"
    url = "/decisions/"
    weight = 2
  [[menu.main]]
    name = "Glossary"
    url = "/glossary/"
    weight = 3
  [[menu.main]]
    name = "Blog Posts"
    url = "/categories/blog_post/"
    weight = 4
  [[menu.main]]
    name = "Research Papers"
    url = "/categories/research_paper/"
    weight = 5
  [[menu.main]]
    name = "Root Cause Analysis"
    url = "/categories/root_cause_analysis/"
    weight = 6