baseURL = "https://thakurajayL.github.io/quality-share/"
languageCode = 'en-us'
title = 'Quality Share: A Curated Library for Engineers'
theme = "ananke"

[params]
  description = "High-signal engineering articles, expertly curated. Because your time is too valuable for anything less."
  # Custom params for data sources
  [params.data]
    pipelineDb = "../pipeline/data/pipeline.db"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Decisions"
    url = "/decisions/"
    weight = 2