name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For pushing the build output to gh-pages
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true needs Git 2.12 or higher)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        working-directory: ./pipeline
        run: poetry install

      - name: Debug list site/content/posts
        run: ls -R site/content/posts

      - name: Update published_content table
        working-directory: ./pipeline
        run: poetry run python src/update_published_content.py

      - name: Generate articles.json
        working-directory: ./pipeline
        run: poetry run python src/generate_site_data.py

      - name: Debug articles.json content
        run: cat site/data/articles.json

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        working-directory: ./site
        run: hugo --minify

      - name: Debug list site/public after build
        run: ls -R site/public

      - name: List site directory after build
        run: ls -R ./site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public
          publish_branch: gh-pages
          force_orphan: true
