name: AI Curation Pipeline

on:
  schedule:
    # Run once a day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        working-directory: ./pipeline
        run: poetry install

      - name: Run pipeline
        working-directory: ./pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPO_NAME: ${{ github.repository }}
        run: poetry run python src/main.py

  notify-on-failure:
    runs-on: ubuntu-latest
    if: failure()
    needs: [run-pipeline]
    steps:
      - name: Send email notification
        uses: sendgrid/sendgrid-action@v3
        with:
          to: ${{ secrets.MAIL_TO }}
          from: 'actions@github.com'
          subject: 'Workflow Failure: ${{ github.workflow }} in ${{ github.repository }}'
          html_content: 'The ${{ github.workflow }} workflow in the ${{ github.repository }} repository has failed. Please check the logs for more details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}